package ai.shreds.domain.entities;

import ai.shreds.domain.exceptions.DomainValidationException;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Domain entity representing an event in the outbox pattern.
 * Used for reliable event publishing with transactional guarantees.
 * Events are stored in the same transaction as business data and published asynchronously.
 */
public class DomainEventOutboxEntity {
    private Long id;
    private final UUID aggregateId;
    private final String aggregateType;
    private final String eventType;
    private final String payload;
    private final LocalDateTime createdAt;
    private boolean processed;
    private LocalDateTime processedAt;

    /**
     * Constructs a new event outbox entity.
     *
     * @param id the event ID (may be null for new events)
     * @param aggregateId the ID of the aggregate that generated the event
     * @param aggregateType the type of the aggregate (e.g. "InventoryItem", "Warehouse")
     * @param eventType the type of the event (e.g. "StockMovementCreated")
     * @param payload the JSON payload of the event
     * @param createdAt when the event was created
     * @param processed whether the event has been processed
     * @param processedAt when the event was processed (may be null)
     */
    public DomainEventOutboxEntity(
            Long id,
            UUID aggregateId,
            String aggregateType,
            String eventType,
            String payload,
            LocalDateTime createdAt,
            boolean processed,
            LocalDateTime processedAt) {
        
        validateConstructorParameters(aggregateId, aggregateType, eventType, payload, createdAt);
        
        this.id = id;
        this.aggregateId = aggregateId;
        this.aggregateType = aggregateType;
        this.eventType = eventType;
        this.payload = payload;
        this.createdAt = createdAt;
        this.processed = processed;
        this.processedAt = processedAt;
    }
    
    private void validateConstructorParameters(
            UUID aggregateId,
            String aggregateType,
            String eventType,
            String payload,
            LocalDateTime createdAt) {
        
        if (aggregateId == null) {
            throw new DomainValidationException("Aggregate ID cannot be null", "aggregateId", null);
        }
        
        if (aggregateType == null || aggregateType.trim().isEmpty()) {
            throw new DomainValidationException(
                "Aggregate type cannot be null or empty", 
                "aggregateType", 
                aggregateType
            );
        }
        
        if (eventType == null || eventType.trim().isEmpty()) {
            throw new DomainValidationException(
                "Event type cannot be null or empty", 
                "eventType", 
                eventType
            );
        }
        
        if (payload == null || payload.trim().isEmpty()) {
            throw new DomainValidationException(
                "Event payload cannot be null or empty", 
                "payload", 
                payload
            );
        }
        
        if (createdAt == null) {
            throw new DomainValidationException("Created at cannot be null", "createdAt", null);
        }
        
        if (createdAt.isAfter(LocalDateTime.now())) {
            throw new DomainValidationException(
                "Created at cannot be in the future", 
                "createdAt", 
                createdAt
            );
        }
    }
    
    /**
     * Factory method to create a new unprocessed event.
     *
     * @param aggregateId the aggregate ID
     * @param aggregateType the aggregate type
     * @param eventType the event type
     * @param payload the event payload as JSON
     * @return a new unprocessed event outbox entity
     */
    public static DomainEventOutboxEntity createNew(
            UUID aggregateId,
            String aggregateType,
            String eventType,
            String payload) {
        
        return new DomainEventOutboxEntity(
                null, // ID will be generated by persistence layer
                aggregateId,
                aggregateType,
                eventType,
                payload,
                LocalDateTime.now(),
                false, // Not processed initially
                null   // Not processed yet
        );
    }
    
    /**
     * Marks this event as processed.
     * Sets the processed flag to true and records the processing timestamp.
     */
    public void markAsProcessed() {
        if (processed) {
            return; // Already processed, no change needed
        }
        
        this.processed = true;
        this.processedAt = LocalDateTime.now();
    }
    
    /**
     * Checks if this event is ready for processing.
     * Events are ready if they are not yet processed.
     *
     * @return true if the event can be processed
     */
    public boolean isReadyForProcessing() {
        return !processed;
    }
    
    /**
     * Checks if this event has been processed.
     *
     * @return true if the event has been processed
     */
    public boolean isProcessed() {
        return processed;
    }
    
    /**
     * Gets the age of this event in seconds since creation.
     *
     * @return the age in seconds
     */
    public long getAgeInSeconds() {
        return java.time.Duration.between(createdAt, LocalDateTime.now()).getSeconds();
    }
    
    /**
     * Checks if this event is stale (older than specified seconds).
     *
     * @param maxAgeSeconds the maximum age in seconds
     * @return true if the event is older than the specified age
     */
    public boolean isStale(long maxAgeSeconds) {
        return getAgeInSeconds() > maxAgeSeconds;
    }
    
    /**
     * Gets the processing delay in seconds (time between creation and processing).
     *
     * @return processing delay in seconds, or null if not processed yet
     */
    public Long getProcessingDelaySeconds() {
        if (processedAt == null) {
            return null;
        }
        return java.time.Duration.between(createdAt, processedAt).getSeconds();
    }
    
    /**
     * Creates a retry event based on this event.
     * Useful when an event fails processing and needs to be retried.
     *
     * @return a new event outbox entity for retry
     */
    public DomainEventOutboxEntity createRetryEvent() {
        return createNew(
                this.aggregateId,
                this.aggregateType,
                this.eventType + "_RETRY",
                this.payload
        );
    }

    // Getters
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public UUID getAggregateId() {
        return aggregateId;
    }

    public String getAggregateType() {
        return aggregateType;
    }

    public String getEventType() {
        return eventType;
    }

    public String getPayload() {
        return payload;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public boolean getProcessed() {
        return processed;
    }

    public LocalDateTime getProcessedAt() {
        return processedAt;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        DomainEventOutboxEntity that = (DomainEventOutboxEntity) o;
        return Objects.equals(id, that.id);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
    
    @Override
    public String toString() {
        return "DomainEventOutboxEntity{" +
                "id=" + id +
                ", aggregateId=" + aggregateId +
                ", aggregateType='" + aggregateType + '\'' +
                ", eventType='" + eventType + '\'' +
                ", processed=" + processed +
                ", createdAt=" + createdAt +
                '}';
    }
}